# Generated by Django 3.1.2 on 2021-01-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210108_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='superhost',
            new_name='superuser',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(error_messages={'unique': 'A user with that username already exists.'}, max_length=254, unique=True),
        ),
    ]
